# 建置
FROM node:22-alpine as build-stage

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# 產生 dist 資料夾
RUN npm run build

# 正式運作
FROM nginx:1.27-alpine as production-stage

# 複製打包好的 Vue 檔案到 Nginx 預設目錄
COPY --from=build-stage /app/dist /usr/share/nginx/html

# 複製 Nginx 設定檔
# 存成 default.conf，這樣 Nginx 啟動時就會自動讀取
COPY cychfront.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]